apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-demo
  template:
    metadata:
      labels:
        app: frontend-demo
    spec:
      containers:
      - name: frontend-demo
        image: lawjac2024/frontend-demo:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  selector:
    app: frontend-demo
  ports:
  - port: 80
    targetPort: 80

